language: python

script:
  - python manage.py test


matrix:
  fast_finish: true
  include:

    - python: 2.7
      install:
        - pip install six
        - pip install django==1.11

    - python: 3.5
      install:
        - pip install six
        - pip install django

    - python: 3.6
      install:
        - pip install six
        - pip install django

    - python: 3.7-dev
      install:
        - pip install six
        - pip install django
