# Generated by Django 2.1.1 on 2018-09-17 15:38
import os
from django.db import migrations
import environize

PATH = 'project/app/fixtures/'


def test_fixture(apps, schema_editor):
    for fixture in ['ham.json', 'bar.json', 'foo.json', 'baz.json']:
        environize.loaddata(apps, os.path.join(PATH, fixture))


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180916_1122'),
    ]

    operations = [
        migrations.RunPython(test_fixture, lambda x, y: None)
    ]
